### ISSUE TITLE
TypeError on arch with awesomewm

### ISSUE THREAD

**Issue by cars10** [pop-os/hidpi-daemon#13]
**Distribution - (run ```cat /etc/os-release```):**
Archlinux 
 
**Issue/Bug Description:**
I used the following package: https://aur.archlinux.org/packages/hidpi-daemon/

But starting hidpi-daemon leads to the following error:

```
/usr/lib/python3.7/site-packages/hidpidaemon/hidpidaemon2.py:34: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, GLib, Gtk
2018-10-11 08:14:23,702  INFO  **** Process start at monotonic time 153.859635257
Traceback (most recent call last):
  File "/usr/lib/hidpi-daemon/hidpi-daemon", line 78, in <module>
    if 'GNOME' not in desktop_session:
TypeError: argument of type 'NoneType' is not iterable

```

Same thing for hidpi-notification:

```
018-10-11 08:14:49,709  INFO  **** Process start at monotonic time 180.018885242
Traceback (most recent call last):
  File "/usr/lib/hidpi-daemon/hidpi-notification", line 168, in <module>
    if 'GNOME' in desktop_session:
TypeError: argument of type 'NoneType' is not iterable

```

**Steps to reproduce (if you know):**

Install the above package on archlinux and run the daemon.

**Expected behavior:**

Daemon should work.

**Other Notes:**
Using awesome windowmanager.

**Comment by djordan2** [comment]
That's not quite the error we'd like to have, but it's not expected to work on awesomewm.  It looks like you don't have the XDG_CURRENT_DESKTOP environment variable set at all.

hidpi-daemon doesn't yet know how to configure things on awesomewm, which is why we check for supported environments. The backend should be compatible with most mutter-based DEs, but a new frontend code is needed for certain DEs still (like Elementary's Pantheon).  If you happen to have a gnome-shell session as an option, you could use that to verify that the hidpi-daemon package in arch is working as intended.

I don't have the time currently to add awesomewm support, but contributions are welcome as long as they don't interfere with functionality in gnome-shell.

**Comment by cars10** [comment]
Okay, thanks. Any plans about adding a readme where information like that would be listed? Reading the repo description "Daemon to manage HiDPI and LoDPI monitors on X" let me think that it works with any DE. Maybe add a list of supported environments?
