### ISSUE TITLE
Hidpi-daemon crashes because nvidia-settings -q CurrentMetaMode fails

### ISSUE THREAD

**Issue by gorghino** [pop-os/hidpi-daemon#38]
**IMPORTANT**
Please attach output of the xrandr command and ~.config/montors.xml to help diagnose the issue.
xrandr and monitors.xml: https://pastebin.com/n1KZ8mHP

(Note there's a typo above in your instructions: ~.config/montors.xml shall be ~/.config/monitors.xml)

 Distribution: *Pop!_OS 20.10*
 
 
 **Related Application and/or Package Version - (run ```apt policy $PACKAGE NAME```):* 
hidpi-daemon: 18.04.6~1594738317~20.10~cfe8850
nvidia-settings 460.39-0ubuntu0.20.10.1
NVIDIA-SMI 460.56
Driver Version: 460.56*

**Issue/Bug Description:**
Hidpi-daemon crashes during boot because nvidia-settings -q CurrentMetaMode fails on my system. 
CurrentMetaMode is not listed in my 'nvidia-settings -q all'

> mar 10 10:07:12 pop-os hidpi-daemon.desktop[3097]: ERROR: Error resolving target specification '' (No targets match target specification), specified in query 'CurrentMetaMode'.
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]: /usr/lib/hidpi-daemon/hidpi-daemon:92: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Th>
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   GObject.threads_init()
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]: 2021-03-10 10:07:12,135  ERROR  Error calling _run_hidpi_autoscaling(None):
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]: Traceback (most recent call last):
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1620, in run_hidpi_autoscaling
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:     return _run_hidpi_autoscaling(model)
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1614, in _run_hidpi_autoscaling
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:     hidpi.run()
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1537, in run
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:     self.set_scaled_display_modes()
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1354, in set_scaled_display_modes
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:     cmd = cmd + self.set_display_scaling(display, layout, force=force, lowdpi_prime=has_lowdpi_prime)
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1271, in set_display_scaling
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:     return self.set_display_scaling_nvidia_settings(display, layout, scale_mode=mode)
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1159, in set_display_scaling_nvidia_settings
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:     display_str = display_str + self.get_nvidia_settings_options(display_name, viewportin, viewportout)
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1069, in get_nvidia_settings_options
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:     output = subprocess.check_output(cmd).decode("utf-8")
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:   File "/usr/lib/python3.8/subprocess.py", line 512, in run
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]:     raise CalledProcessError(retcode, process.args,
> mar 10 10:07:12 pop-os hidpi-daemon.desktop[2960]: subprocess.CalledProcessError: Command '['nvidia-settings', '-q', 'CurrentMetaMode']' returned non-zero exit status 1.

**Other Notes:**

```
             /////////////                gorgo@pop-os 
         /////////////////////            ------------ 
      ///////*767////////////////         OS: Pop!_OS 20.10 x86_64 
    //////7676767676*//////////////       Host: Blade 15 Advanced Model (Early 2020) - RZ09-033 5.04 
   /////76767//7676767//////////////      Kernel: 5.8.0-7642-generic 
  /////767676///*76767///////////////     Uptime: 1 hour 
 ///////767676///76767.///7676*///////    Packages: 2974 (dpkg), 29 (flatpak) 
/////////767676//76767///767676////////   Shell: bash 5.0.17 
//////////76767676767////76767/////////   Resolution: 4384x2466 
///////////76767676//////7676//////////   DE: GNOME 3.38.3 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Pop-dark [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: Intel i7-10875H (16) @ 2.300GHz 
    /////767676767676767676767/////       GPU: NVIDIA GeForce RTX 2080 SUPER Mobile / Max-Q 
      ///////////////////////////         GPU: Intel UHD Graphics 
         /////////////////////            Memory: 4965MiB / 15867MiB 
             /////////////

```

**Comment by jacobgkau** [comment]
This sounds like it may be a duplicate of https://github.com/pop-os/hidpi-daemon/issues/34. Does the issue occur in NVIDIA mode or Integrated mode, or only in the default Hybrid mode?

**Comment by gorghino** [comment]
Yes. I'll close as it's a duplicate ;)
